version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8000:80
    volumes:
      - .:/var/www/html
    environment:
      - APP_ENV=local
      - APP_DEBUG=true
      - APP_KEY=base64:3OEA9BNrhG0JIcx1Ht8osseq8tUv9k1g8cFHtB5od30=
      - DB_CONNECTION=mysql
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=crud_test
      - DB_USERNAME=root
      - DB_PASSWORD=
    depends_on:
      - db
    networks:
      - app-network

  db:
    image: mysql:8.0
    ports:
      - 3306:3306
    environment:
      - MYSQL_DATABASE=crud_test
      - MYSQL_USER=root
      - MYSQL_PASSWORD=
      - MYSQL_ROOT_PASSWORD=
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - app-network
      
  phpmyadmin:
      image: phpmyadmin/phpmyadmin
      ports:
        - 8080:80
      environment:
        PMA_HOST: db
        MYSQL_ROOT_PASSWORD: your_root_password
networks:
  app-network:

volumes:
  db-data:
