version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 80:80
    depends_on:
      - db
    volumes:
      - .:/var/www/html
    environment:
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=crud_test
      - DB_USERNAME=root
      - DB_PASSWORD=crud_test
      - MYSQL_ROOT_PASSWORD=crud_test


  db:
    image: mysql:8.0
    ports:
      - 3306:3306
    environment:
      - MYSQL_DATABASE=crud_test
      - DB_USERNAME=root
      - DB_PASSWORD=crud_test
      - MYSQL_ROOT_PASSWORD=crud_test
    volumes:
      - dbdata:/var/lib/mysql


volumes:
  dbdata:
